#!/bin/sh
#
# Runs during git flow hotfix finish and a tag message is given
#
# Positional arguments:
# $1    Message
# $2    Full version
#
# Return MESSAGE
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
MESSAGE="$1"

# Implement your script here.

MESSAGE=${MESSAGE/%%TAG_VERSION%%/"$2"}

# Return the MESSAGE
echo "${MESSAGE}"
exit 0
