#!/bin/sh
#
# Runs before git flow hotfix finish
#
# Positional arguments:
# $1    The version (including the version prefix)
# $2    The origin remote
# $3    The full branch name (including the feature prefix)
#
VERSION=$1
ORIGIN=$2
BRANCH=$3

# Implement your script here.
. "$HOOKS_DIR"/gitflow-functions
ROOTDIR=$(git rev-parse --show-toplevel)

# Update the AUTHORS file.
gitflow_update_authors

sed -i '0,/Stable tag: .*/s/^Stable tag: .*/Stable tag: '$VERSION'/' $ROOTDIR/readme.txt

gitflow_update_version $VERSION

# To terminate the git-flow action, return a non-zero exit code.
exit 0
